# Should perform a recover of the setup using the ini file.
recovered: "False"

# Should the ansible play ignore errors on the way or not.
ignore: "yes"

# Should we use the partial import flag when registering VMs and Templates.
partial_import: "True"

# Indicates which host should the ansible script be executed (Optional values are primary and secondary).
host: 'primary'
