- name: Fetch unregistered Templates from storage domain
  ovirt_storage_templates_facts:
      nested_attributes: "id"
      unregistered: True
      storage_domain: "{{ storage.name }}"
      auth: "{{ ovirt_auth }}"

- name: Register unregistered Template
  ovirt_templates:
      state: registered
      storage_domain: "{{ storage.name }}"
      id: "{{ unreg_template.id }}"
      # TODO: cluster should be part of VM's OVF
      allow_partial_import: "{{ partial_import | default(True) }}"
      auth: "{{ ovirt_auth }}"
      cluster_mappings:
        - source:
          - name: test
          dest:
          - name: cluster44

      # TODO: We should set a flag
      # - fail: msg="The execution has failed because of errors."
      #  when: flag == "failed"
      #
      #  - name: Set flag
      #  set_fact: flag = failed
      #  when: "'FAILED' in command_result.stderr"
  # The main task already declared ignore errors so that might be redundant to put it here
  # ignore_errors: "{{ ignore | default(yes) }}"
  with_items: "{{ ovirt_storage_templates }}"
  # We use loop_control so storage.name will not be overriden by the nested loop.
  loop_control:
      loop_var: unreg_template

