- name: Add NFS storage domain
  ovirt_storage_domains:
      name: "{{ nfs_storage['dr_' + dr_target_host + '_name'] }}"
      host: "{{ ovirt_hosts[0].name }}"
      data_center: "{{ nfs_storage['dr_' + dr_target_host + '_dc_name'] }}"
      auth: "{{ ovirt_auth }}"
      nfs:
          path: "{{ nfs_storage['dr_' + dr_target_host + '_path'] }}"
          address: "{{ nfs_storage['dr_' + dr_target_host + '_address'] }}"
